import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/app/_landingPageComponents/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full flex">
      <Header />
      <div className="w-screen">{children}</div>
    </div>
  );
}
